/*
 * Swagger K8S Quartermaster - OpenAPI 3.0
 *
 * This is the API design of the K8S quartermaster tool, the goal is to effectively obtain K8S resources, which can then be used for YAML configurations or other pruposes.  Some useful links: - [Swagger](https://swagger.io/) - [Kubernetes](https://kubernetes.io/docs/concepts/configuration/)
 *
 * API version: 0.0.1
 * Contact: rik.van.brakel@sue.nl
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/brikkel/quartermaster-api/go"
)

func main() {
	log.Printf("Server started")

	KindsAPIService := openapi.NewKindsAPIService()
	KindsAPIController := openapi.NewKindsAPIController(KindsAPIService)

	router := openapi.NewRouter(KindsAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
