/*
 * Swagger K8S Quartermaster - OpenAPI 3.0
 *
 * This is the API design of the K8S quartermaster tool, the goal is to effectively obtain K8S resources, which can then be used for YAML configurations or other pruposes.  Some useful links: - [Swagger](https://swagger.io/) - [Kubernetes](https://kubernetes.io/docs/concepts/configuration/)
 *
 * API version: 0.0.1
 * Contact: rik.van.brakel@sue.nl
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
)



// KindsAPIRouter defines the required methods for binding the api requests to a responses for the KindsAPI
// The KindsAPIRouter implementation should parse necessary information from the http request,
// pass the data to a KindsAPIServicer to perform the required actions, then write the service results to the http response.
type KindsAPIRouter interface { 
	GetKinds(http.ResponseWriter, *http.Request)
}


// KindsAPIServicer defines the api actions for the KindsAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type KindsAPIServicer interface { 
	GetKinds(context.Context) (ImplResponse, error)
}
