openapi: 3.0.2
info:
  contact:
    email: rik.van.brakel@sue.nl
  description: |-
    This is the API design of the K8S quartermaster tool, the goal is to effectively obtain K8S resources, which can then be used for YAML configurations or other pruposes.

    Some useful links:
    - [Swagger](https://swagger.io/)
    - [Kubernetes](https://kubernetes.io/docs/concepts/configuration/)
  license:
    name: Rights reserved
    url: http:/www.sue.nl
  termsOfService: https://sue.nl
  title: Swagger K8S Quartermaster - OpenAPI 3.0
  version: 0.0.1
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: http://localhost:8080/v3
tags:
- description: Kind related endpoints
  externalDocs:
    description: Find out more
    url: http://k8s.io
  name: kinds
- description: Resource endpoints
  externalDocs:
    description: Find out more
    url: http://k8s.io
  name: resource
paths:
  /kinds:
    get:
      description: Returns a map of status codes to quantities
      operationId: getKinds
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Kinds'
                type: array
          description: successful operation
      summary: Returns pet inventories by status
      tags:
      - kinds
  /parameters/{versionPath}/{fullResourceName}:
    get:
      description: Returns a list of paramaters of a given resource
      operationId: getParameters
      parameters:
      - description: full name of the resource
        explode: false
        in: path
        name: fullResourceName
        required: true
        schema:
          type: string
        style: simple
      - description: path to the api version
        explode: false
        in: path
        name: versionPath
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Resource'
                type: array
          description: successful operation
      summary: Gives parameters of a resource
      tags:
      - resource
components:
  requestBodies:
    Kinds:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Kinds'
      description: Pet object that needs to be added to the store
  schemas:
    Kinds:
      example:
        apiVersionPath: api/v1
        kinds:
        - name: pod
          description: this is a pod
          type: object
        - name: pod
          description: this is a pod
          type: object
      properties:
        apiVersionPath:
          example: api/v1
          type: string
        kinds:
          items:
            $ref: '#/components/schemas/Kind'
          type: array
      required:
      - apiVersionPath
    Kind:
      example:
        name: pod
        description: this is a pod
        type: object
      properties:
        name:
          example: pod
          type: string
        description:
          example: this is a pod
          type: string
        type:
          example: object
          type: string
    Resource:
      example:
        Path: ""
        Type: ""
        Description: ""
        Parameters:
        - Type: object
          Description: this is a container
          Required: false
          Items:
          - Type: ""
            ResourceReference: ""
            Default: ""
          - Type: ""
            ResourceReference: ""
            Default: ""
          ResourceReference: ""
          Default: ""
          Name: container
        - Type: object
          Description: this is a container
          Required: false
          Items:
          - Type: ""
            ResourceReference: ""
            Default: ""
          - Type: ""
            ResourceReference: ""
            Default: ""
          ResourceReference: ""
          Default: ""
          Name: container
        FullResourceName: ""
        Name: ""
      properties:
        FullResourceName:
          example: ""
          type: string
        Path:
          example: ""
          type: string
        Name:
          example: ""
          type: string
        Description:
          example: ""
          type: string
        Type:
          example: ""
          type: string
        Parameters:
          items:
            $ref: '#/components/schemas/Parameter'
          type: array
    Parameter:
      example:
        Type: object
        Description: this is a container
        Required: false
        Items:
        - Type: ""
          ResourceReference: ""
          Default: ""
        - Type: ""
          ResourceReference: ""
          Default: ""
        ResourceReference: ""
        Default: ""
        Name: container
      properties:
        Name:
          example: container
          type: string
        Description:
          example: this is a container
          type: string
        Type:
          example: object
          type: string
        Required:
          example: false
          type: boolean
        Default:
          example: ""
          type: string
        ResourceReference:
          example: ""
          type: string
        Items:
          items:
            $ref: '#/components/schemas/Item'
          type: array
    Item:
      example:
        Type: ""
        ResourceReference: ""
        Default: ""
      properties:
        Default:
          example: ""
          type: string
        ResourceReference:
          example: ""
          type: string
        Type:
          example: ""
          type: string
